apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: MONGO_COLLECTION_NAME
              value: events
            - name: MONGO_DB_NAME
              value: kafka_events
            - name: MONGO_URI
              value: mongodb://mongodb:27017
            - name: PORT
              value: "3000"
          image: ekrem0691/api
          name: api
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
