apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: consumer
    spec:
      containers:
        - args:
            - node
            - index.js
          env:
            - name: KAFKA_BROKER
              value: broker:9092
            - name: KAFKA_GROUP_ID
              value: consumer_group_1
            - name: KAFKA_TOPIC
              value: events_topic
            - name: MONGO_COLLECTION_NAME
              value: events
            - name: MONGO_DB_NAME
              value: kafka_events
            - name: MONGO_URI
              value: mongodb://mongodb:27017
          image: ekrem0691/consumer
          name: consumer
      restartPolicy: Always
