apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: producer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: producer
    spec:
      containers:
        - args:
            - node
            - index.js
          env:
            - name: KAFKA_BROKER
              value: broker:9092
            - name: KAFKA_TOPIC
              value: events_topic
          image: ekrem0691/producer:latest
          name: producer
      restartPolicy: Always
