# Consumer Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-consumer
spec:
  selector:
    app: kafka-mongodb-nodejs-consumer
  ports:
    - protocol: TCP
      port: {{ .Values.consumer.service.port }}
      targetPort: {{ .Values.consumer.service.port }}

---

# Producer Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-producer
spec:
  selector:
    app: kafka-mongodb-nodejs-producer
  ports:
    - protocol: TCP
      port: {{ .Values.producer.service.port }}
      targetPort: {{ .Values.producer.service.port }}

---

# API Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec
