apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  labels:
    app: rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: api
        image: ekrem0691/api:latest
        env:
        - name: MONGO_URI
          value: mongodb-service:27017
        - name: MONGO_DB_NAME
          value: kafka_events
        - name: MONGO_COLLECTION_NAME
          value: events
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: rest-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
