apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: ekrem0691/consumer:latest
        env:
        - name: KAFKA_BROKER
          value: kafka-service:9092
        - name: KAFKA_TOPIC
          value: events_topic
        - name: KAFKA_GROUP_ID
          value: consumer_group_1
        - name: MONGO_URI
          value: mongodb-service:27017
        - name: MONGO_DB_NAME
          value: kafka_events
        - name: MONGO_COLLECTION_NAME
          value: events
